-- 처음 컨테이너를 만들 때 한 번만 돈다 (gvenzl/oracle-xe 의 /container-entrypoint-initdb.d).
-- SYS 로 실행되므로 XEPDB1 로 옮기고, 테이블 주인을 팀 사용자 CAPSTONE 으로 둔다.
-- 원본: 노션 DB 모델링 페이지의 DDL (9/28 오라클판). 2차에서 posting.is_excluded 추가.
-- 기준 데이터(job·skill·skill_alias)는 한글 깨짐을 피하려고 여기서 넣지 않고 크롤러 앱이 넣는다.
SET SQLBLANKLINES ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = CAPSTONE;

-- Oracle 21c XE · 설계 초안 (9/28 회의에서 확정)
-- 테이블은 XEPDB1 안의 팀 전용 사용자(스키마)에 만든다. system 에 만들지 않는다
-- Flyway 를 쓰면 이 파일이 V1__init.sql 이 된다
-- 한 번 적용한 V1 은 고치지 않는다. 바꿀 것은 새 V 파일에 ALTER TABLE 로 넣는다
-- 21c 에는 BOOLEAN 칸이 없다 → NUMBER(1) + CHECK (0, 1). ENUM 도 없다 → VARCHAR2 + CHECK
-- 문자열 길이는 글자 수(CHAR)로 센다. 기본(BYTE)이면 한글 한 글자가 3바이트라 넘친다
-- 오라클은 빈 문자열 '' 을 NULL 로 저장한다. NOT NULL 칸에 '' 를 넣으면 오류
-- DEFAULT 는 SQL 로 직접 넣을 때만 쓰인다. JPA 로 넣는 NOT NULL 칸은 엔티티에서 채운다

CREATE TABLE job (
  job_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  saramin_code     NUMBER(10) NOT NULL,            -- 84 백엔드 · 92 프론트엔드 · 2232 풀스택
  name             VARCHAR2(30 CHAR) NOT NULL,
  sort_order       NUMBER(10) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_job PRIMARY KEY (job_id),
  CONSTRAINT uk_job_code UNIQUE (saramin_code)
);

CREATE TABLE company (
  company_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  saramin_csn      VARCHAR2(64 CHAR),              -- 목록 회사 링크의 csn, 없으면 NULL (NULL 은 여러 개여도 UNIQUE 통과)
  name             VARCHAR2(100 CHAR) NOT NULL,
  group_name       VARCHAR2(50 CHAR),              -- span.main_corp (예: 토스그룹)
  size_label       VARCHAR2(20 CHAR),              -- span.info_stock (예: 대기업)
  CONSTRAINT pk_company PRIMARY KEY (company_id),
  CONSTRAINT uk_company_csn UNIQUE (saramin_csn)
);

CREATE TABLE posting (
  posting_id       NUMBER(19) NOT NULL,            -- 사람인 공고번호 rec_idx (IDENTITY 아님)
  company_id       NUMBER(10) NOT NULL,
  title            VARCHAR2(300 CHAR) NOT NULL,
  url              VARCHAR2(500 CHAR) NOT NULL,   -- 사람인 원문 주소, ①이 공고번호로 만들어 넣음
  career_type      VARCHAR2(20),                   -- NEW · EXPERIENCED · NEW_OR_EXP · ANY
  exp_min          NUMBER(10),                     -- 경력 최소 연수
  exp_max          NUMBER(10),                     -- 경력 최대 연수, 상한 없으면 NULL
  education        VARCHAR2(30 CHAR),
  employment_type  VARCHAR2(50 CHAR),              -- 정규직, 계약직 …
  region           VARCHAR2(100 CHAR),             -- "서울 강남구 외"
  posted_on        DATE,                           -- 접수 시작일 (상세 .jv_howto). 오라클 DATE 는 시각도 담는다 → 자정으로 넣음
  deadline_type    VARCHAR2(20) NOT NULL,          -- ①이 목록의 마감 표기로 정함
  deadline_on      DATE,                           -- ③이 접수 기간으로 채움, 채용시·상시·수시면 NULL
  is_headhunting   NUMBER(1) DEFAULT 0 NOT NULL,   -- ① 회사 칸의 "헤드헌팅"
  is_mass_hiring   NUMBER(1) DEFAULT 0 NOT NULL,   -- 여러 직무를 한꺼번에 뽑는 대량 공채, ④에서 계산 (기준은 회의에서 정할 부분)
  is_closed        NUMBER(1) DEFAULT 0 NOT NULL,
  is_excluded      NUMBER(1) DEFAULT 0 NOT NULL,   -- 통계 제외(비개발·반도체 설계). ④가 매번 다시 계산. 9/29 추가
  closed_at        TIMESTAMP,                      -- 되살리면 NULL
  first_seen_at    TIMESTAMP NOT NULL,
  last_seen_at     TIMESTAMP NOT NULL,
  list_modified_at TIMESTAMP,                      -- 목록의 "N분/N시간 전 수정"으로 계산한 시각
  detail_at        TIMESTAMP,                      -- 상세를 마지막으로 성공한 시각, NULL = 아직 못 받음
  detail_fail_cnt  NUMBER(10) DEFAULT 0 NOT NULL,  -- ③ 실패 횟수. 성공, 새 수정, ④가 raw 파일이 없어 다시 받게 할 때 0
  CONSTRAINT pk_posting PRIMARY KEY (posting_id),
  CONSTRAINT ck_posting_career CHECK (career_type IN ('NEW', 'EXPERIENCED', 'NEW_OR_EXP', 'ANY')),
  CONSTRAINT ck_posting_deadline CHECK (deadline_type IN ('DATE', 'UNTIL_FILLED', 'ALWAYS', 'ROLLING')),
  CONSTRAINT ck_posting_flags CHECK (is_headhunting IN (0, 1) AND is_mass_hiring IN (0, 1) AND is_closed IN (0, 1)),
  CONSTRAINT ck_posting_excluded CHECK (is_excluded IN (0, 1)),
  CONSTRAINT fk_posting_company FOREIGN KEY (company_id) REFERENCES company (company_id)
);
-- 오라클은 외래 키에 인덱스를 자동으로 만들지 않는다
-- (주석은 문장 뒤 같은 줄에 두지 않는다: sqlplus 가 세미콜론을 문장 끝으로 못 알아본다)
CREATE INDEX idx_posting_company ON posting (company_id);
CREATE INDEX idx_posting_open_posted ON posting (is_closed, posted_on);
CREATE INDEX idx_posting_open_deadline ON posting (is_closed, deadline_on);

CREATE TABLE posting_job (
  posting_id       NUMBER(19) NOT NULL,
  job_id           NUMBER(10) NOT NULL,
  CONSTRAINT pk_posting_job PRIMARY KEY (posting_id, job_id),
  CONSTRAINT fk_pj_posting FOREIGN KEY (posting_id) REFERENCES posting (posting_id),
  CONSTRAINT fk_pj_job FOREIGN KEY (job_id) REFERENCES job (job_id)
);
CREATE INDEX idx_pj_job ON posting_job (job_id, posting_id);

CREATE TABLE skill (
  skill_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  saramin_code     NUMBER(10),                     -- 코드표에 없는 기술(Next.js 등)은 NULL
  name             VARCHAR2(50 CHAR) NOT NULL,     -- 화면에 보이는 이름
  category         VARCHAR2(20) NOT NULL,
  CONSTRAINT pk_skill PRIMARY KEY (skill_id),
  CONSTRAINT uk_skill_code UNIQUE (saramin_code),
  CONSTRAINT uk_skill_name UNIQUE (name),
  CONSTRAINT ck_skill_category CHECK (category IN ('LANGUAGE', 'FRAMEWORK', 'DATABASE', 'CLOUD_INFRA',
                                                   'DEVOPS_TOOL', 'MOBILE', 'AI_DATA', 'ETC'))
);

CREATE TABLE skill_alias (
  alias            VARCHAR2(60 CHAR) NOT NULL,     -- 소문자로 저장: reactjs, 리액트
  skill_id         NUMBER(10) NOT NULL,
  text_match       NUMBER(1) DEFAULT 1 NOT NULL,   -- 0 = 태그·검색에만 (go, r, c, es, 뷰, 깃, 펄, 노드, 넥스트, 다트)
  CONSTRAINT pk_skill_alias PRIMARY KEY (alias),
  CONSTRAINT ck_alias_text_match CHECK (text_match IN (0, 1)),
  CONSTRAINT fk_alias_skill FOREIGN KEY (skill_id) REFERENCES skill (skill_id)
);
CREATE INDEX idx_alias_skill ON skill_alias (skill_id);

CREATE TABLE posting_skill (
  posting_id       NUMBER(19) NOT NULL,
  skill_id         NUMBER(10) NOT NULL,
  source           VARCHAR2(20) NOT NULL,          -- 본문을 받기로 하면 BODY 를 CHECK 에 추가
  CONSTRAINT pk_posting_skill PRIMARY KEY (posting_id, skill_id, source),
  CONSTRAINT ck_ps_source CHECK (source IN ('TAG', 'REQUIRED', 'PREFERRED')),
  CONSTRAINT fk_ps_posting FOREIGN KEY (posting_id) REFERENCES posting (posting_id),
  CONSTRAINT fk_ps_skill FOREIGN KEY (skill_id) REFERENCES skill (skill_id)
);
CREATE INDEX idx_ps_skill ON posting_skill (skill_id, posting_id);

CREATE TABLE job_skill_stat (
  calc_date        DATE NOT NULL,                  -- 자바에서 넘긴 한국 날짜
  job_id           NUMBER(10) NOT NULL,
  skill_id         NUMBER(10) NOT NULL,
  posting_cnt      NUMBER(10) NOT NULL,            -- 이 기술이 나온 실제 공고 수
  job_total        NUMBER(10) NOT NULL,            -- 기술 정보가 있는 공고 수(실제 건수): 진행 중 + 상세 받음 + 통계 제외 아님 + 기술 1개 이상
  ratio            NUMBER(5,4) NOT NULL,           -- 가중 비율: 여러 직무 공고를 1/k 로 나눠 셈 → posting_cnt / job_total 과 다르다 (9/29 변경)
  rank_no          NUMBER(10) NOT NULL,            -- ROW_NUMBER, 동률이어도 겹치지 않음
  CONSTRAINT pk_job_skill_stat PRIMARY KEY (calc_date, job_id, skill_id),
  CONSTRAINT fk_stat_job FOREIGN KEY (job_id) REFERENCES job (job_id),
  CONSTRAINT fk_stat_skill FOREIGN KEY (skill_id) REFERENCES skill (skill_id)
);
CREATE INDEX idx_stat_rank ON job_skill_stat (calc_date, job_id, rank_no);

CREATE TABLE crawl_run (
  run_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  started_at       TIMESTAMP NOT NULL,
  finished_at      TIMESTAMP,
  status           VARCHAR2(10) NOT NULL,          -- RUNNING이 있으면 새로 시작 안 함, 수집을 켠 앱이 뜰 때 남은 RUNNING은 FAILED로
  list_complete    NUMBER(1) DEFAULT 0 NOT NULL,   -- 세 직무 목록을 끝 쪽까지 받았는지. 0이면 ②는 마감일 지난 공고만 닫음
  list_cnt         NUMBER(10) DEFAULT 0 NOT NULL,  -- 목록에서 본 공고
  new_cnt          NUMBER(10) DEFAULT 0 NOT NULL,  -- 상세를 받은 공고 (새 공고·수정된 공고)
  closed_cnt       NUMBER(10) DEFAULT 0 NOT NULL,  -- 마감 처리한 공고
  fail_cnt         NUMBER(10) DEFAULT 0 NOT NULL,  -- 상세를 못 받은 공고
  note             VARCHAR2(500 CHAR),
  CONSTRAINT pk_crawl_run PRIMARY KEY (run_id),
  CONSTRAINT ck_run_status CHECK (status IN ('RUNNING', 'DONE', 'FAILED')),
  CONSTRAINT ck_run_complete CHECK (list_complete IN (0, 1))
);

-- 로그인 붙일 때 추가 (지금은 만들지 않음)
-- app_user   (user_id PK, email UQ, password_hash, desired_job_id → job)
-- user_skill (user_id → app_user, skill_id → skill)       PK (user_id, skill_id)
-- bookmark   (user_id → app_user, posting_id → posting, created_at)  PK (user_id, posting_id)

EXIT
